### ISSUE TITLE
Week 13 interacting with a website labs ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#16]
I accidentally put week 11 as the comment for those labs but it's still under the week 13 folder

**Comment by cethenmc** [comment]
Looks good!  8 out of 8

**Comment by cethenmc** [comment]
I forgot to tell you that you did not print out the title as asked in 2C.  you only printed the links.  You don't have to re-submit, but you will want to add that part on your own to have it correct.  Thanks.  Chris

**Comment by iimckenney-matc** [comment]
I thought I did add the titles, aren't FAQ and T-shirts! the titles here? [cid:2e1ced4a-e00e-4633-a542-8af253de0609]
________________________________
