### ISSUE TITLE
week 14 json lab ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#17]

**Comment by cethenmc** [comment]
Very nice.  I like how you handled the response coming back as a 404, but are you sure the print in your else does exactly what you want it to do?  Were you able to figure out a way to test it?

8 out of 8 for meeting all of the requirements.

**Comment by iimckenney-matc** [comment]
Thank you! I did try it out, if you put in any sort of invalid IP it will pop up the error message that you would get if you were to type it in the address bar of your browser, except without the error code and title. I just put in 4 digits for one of the octets in an IP address to test it.
________________________________

**Comment by cethenmc** [comment]
Great.  I wanted to ensure you knew it would not return the error code and title along with it.  It makes me more pleased that you knew that!  Nice work!

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>
