### ISSUE TITLE
Python Scripting Fall 2022 final-exam.py ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#18]

**Comment by cethenmc** [comment]
Wow!  It has been a true pleasure to have you in my classroom.  Thanks for the great questions.  100 out of 100 on the Final Project!

I will try to mess with that dictionary later this week.  I am pretty sure I know what is going on, but I said that twice already and was wrong in both cases:-).

**Comment by iimckenney-matc** [comment]
Yay! That's what I'm talking about! It's been great to be in your classroom. Despite this being your first semester back teaching you did great and I'm sure you'll only do better from here.

Would you be willing to be a reference for me in the future? Also, I just finished polishing my linked in profile and was wondering if you'd possibly give me some feedback.
________________________________

**Comment by cethenmc** [comment]
Of course.  I am happy to be a reference.

I think the best way to check out your profile is to have you connect with me.  Feel free to send a connection my way.  I will check it out then.

Thanks.

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>
