### ISSUE TITLE
String Formatting lab script is ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#3]

**Comment by cethenmc** [comment]
Hi, Jackson.  Next time it may help to download the Word document assignment.  Technically, you should have had spaces between every "][" in #12 and 13.  Additionally, you should have had the same number of spaces in #13 as there were dollar signs in #12.  Please be more careful in week 4.  I will deduct it in the future.  ~Chris
