### ISSUE TITLE
files.py for File Data Interactions lab is ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#5]
that last one was tough

**Comment by cethenmc** [comment]
Hi, Jackson.  A couple of issues I notice.  You will want to resubmit this one.

You did not write an explanation of what the length represents through a print for #1 and #2.  #3 is not following the request to "save the full file contents one line at a time to a variable."  Please reach out if you have questions.  I know you were not planning to attend this Thursday, so if you want to book a time through Blackboard (the link is under Instructor Contact), then please do.  Thanks.  ~Chris

**Comment by cethenmc** [comment]
I will add that I am marking a 4 out of 8 in the grade book for now to have something there, but I expect you will turn it in fixed for full credit.  Thanks. ~Chris

**Comment by iimckenney-matc** [comment]
re-pushed files.py in week5 folder with the changes made

**Comment by cethenmc** [comment]
Nice job.  Full credit.
